---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daab-ping
  namespace: krdlab
  labels:
    app: daab-ping
spec:
  selector:
    matchLabels:
      app: daab-ping
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: daab-ping
    spec:
      containers:
        - name: daab-ping
          image: krdlab/daab-ping:v0.1.3
          # * NOTE: タグが latest だと Docker Hub から取ろうとする
          # * https://kubernetes.io/docs/setup/learning-environment/minikube/#use-local-images-by-re-using-the-docker-daemon
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
          env:
          - name: REDIS_URL
            value: redis://redis-master:6379/daab
          - name: HUBOT_DIRECT_TOKEN
            valueFrom:
              secretKeyRef:
                name: daab-secrets
                key: HUBOT_DIRECT_TOKEN
                # * NOTE: secret の作り方
                # * https://cloud.google.com/kubernetes-engine/docs/concepts/secret?hl=ja
                # *
                # * 1. daab login
                # * 2. kubectl create secret generic daab-secrets --from-env-file daab-ping/.env -n krdlab
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: daab-ping-webhook
  namespace: krdlab
  labels:
    app: daab-ping
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: daab-ping
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: daab-ping-webhook
  namespace: krdlab
spec:
  rules:
    - host: daab-ping-webhook.10.0.1.23.nip.io
    #- host: daab-ping-webhook.192.168.3.8.nip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: daab-ping-webhook
              servicePort: 8080
